version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8100:80"
    volumes:
      - ../:/var/www/html/
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
    volumes:
      - ../:/var/www/html/
    depends_on:
      - symfony-todo-rest-database
    environment:
      PHP_CS_FIXER_IGNORE_ENV: "true" # necessary until full PHP 8 support in php-cs-fixer
    stdin_open: true
    tty: true
  symfony-todo-rest-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5566:5432"