name: validate-code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.0']
        phpuniturl: ["https://raw.githubusercontent.com/symfony/recipes/master/symfony/phpunit-bridge/4.3/bin/phpunit"]

    name: PHP ${{ matrix.php }} Test on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Code check
        run: composer check
        env:
          PHP_CS_FIXER_IGNORE_ENV: "true" # necessary until full PHP 8 support in php-cs-fixer

      - name: Check phpunit file existence
        if: success()
        id: check-files
        uses: andstor/file-existence-action@v1
        with:
          files: "bin/phpunit"

      - name: Get PHPUnit-Bridge Recipe
        if: success() && steps.check-files.outputs.files_exists == 'false'
        run: |
          mkdir -p bin
          cd bin
          rm -f phpunit
          wget ${{ matrix.phpuniturl }}
          cd ../

      - name: Tests
        run: php bin/phpunit